# FROM php:8.3.7RC1-zts-alpine3.19

# COPY Capacitaciones/ /var/www/html/Capacitaciones/
# #COPY vhost.conf /etc/apache2/sites-available/000-default.conf

# WORKDIR /var/www/html/Capacitaciones
# EXPOSE 8000

# RUN docker-php-ext-install pdo pdo_mysql

# CMD ["php", "-S", "0.0.0.0:8000"]

# FROM php:8.3.7RC1-zts-alpine3.19

# # Instalar extensiones PHP necesarias para Laravel
# RUN docker-php-ext-install pdo pdo_mysql

# WORKDIR /var/www/html/Capacitaciones

# Dockerfile.yaml

# Usar la imagen de PHP 8.3.7RC1-zts-alpine3.19
FROM php:8.3.7RC1-zts-alpine3.19

# Instalar dependencias necesarias
RUN apk add --no-cache \
    bash \
    curl \
    git \
    nodejs \
    npm \
    libpq \
    postgresql-dev \
    libpng \
    libpng-dev \
    jpeg-dev \
    libjpeg \
    libjpeg-turbo-dev \
    freetype \
    freetype-dev \
    libzip-dev \
    zlib-dev

# Instalar Composer
RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

# Configurar la carpeta de trabajo
WORKDIR /var/www/html/Capacitaciones/

# Copiar el código de la aplicación Laravel
COPY Capacitaciones/ /var/www/html/Capacitaciones/

# Instalar dependencias de PHP y de Laravel
RUN composer install

# Configurar la conexión a la base de datos
ENV DB_CONNECTION=mysql
ENV DB_HOST=192.169.10.186
ENV DB_PORT=3306
ENV DB_DATABASE=M700_NOM
ENV DB_USERNAME=nelectronica
ENV DB_PASSWORD=Andina$2020$

# Exponer el puerto si es necesario
# EXPOSE 80

# Comando para ejecutar la aplicación Laravel
CMD ["php", "artisan", "serve", "--host=0.0.0.0"]