# Usar la imagen de PHP 8.3.7RC1-zts-alpine3.19
FROM php:8.3.7RC1-zts-alpine3.19

# Instalar dependencias necesarias
RUN apk add --no-cache \
    bash \
    curl \
    git \
    nodejs \
    npm \
    libpq \
    postgresql-dev \
    libpng \
    libpng-dev \
    jpeg-dev \
    libjpeg \
    libjpeg-turbo-dev \
    freetype \
    freetype-dev \
    libzip-dev \
    zlib-dev 

# Instalar Composer
# RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

# Configurar Apache
RUN sed -i 's#^DocumentRoot ".*#DocumentRoot "/var/www/html/public"#' /etc/apache2/httpd.conf
RUN sed -i 's#AllowOverride none#AllowOverride All#' /etc/apache2/httpd.conf
RUN sed -i 's#^ServerRoot.*#ServerRoot "/etc/apache2"#' /etc/apache2/httpd.conf
RUN echo "Include /etc/apache2/extra/httpd-vhosts.conf" >> /etc/apache2/httpd.conf

# Copiar el código de la aplicación Laravel
COPY /Capacitaciones /var/www/html/Capacitaciones

# Instalar dependencias de PHP y de Laravel
# RUN composer install

# Configurar la conexión a la base de datos
ENV DB_CONNECTION=mysql
ENV DB_HOST=192.169.10.186
ENV DB_PORT=3306
ENV DB_DATABASE=M700_NOM
ENV DB_USERNAME=nelectronica
ENV DB_PASSWORD=Andina$2020$

# Exponer el puerto si es necesario
# EXPOSE 80

# Comando para ejecutar Apache y la aplicación Laravel
CMD ["/usr/sbin/httpd", "-D", "FOREGROUND"]
